name: deploy cool walrus
on:
  workflow_dispatch:
    inputs:
      EPOCHS:
        description: 'Epochs to keep the site alive'
        required: false
        default: '1'
      SUI_NETWORK:
        description: 'Sui network to deploy to'
        required: false
        default: 'mainnet'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: deploy site
        uses: MystenLabs/walrus-sites/.github/actions/deploy@nt/sew-289-gh-action-support-wallet-exported-keys
        with:
          SUI_NETWORK: ${{ inputs.SUI_NETWORK }}
          SUI_BECH32_PRIVATE_KEY: ${{ secrets.SUI_BECH32_PRIV_KEY }}
          DIST: site_dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EPOCHS: ${{ inputs.EPOCHS }}
